services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\Symfony\RuntimeContextBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'

  Tourze\Symfony\RuntimeContextBundle\Service\ContextServiceInterface:
    class: Tourze\Symfony\RuntimeContextBundle\Service\DefaultContextService
    public: true
